
user_list:
    path: /users
    controller: App\Controller\UserController::listUsers
    methods: [GET]

user_preflight:
    path: /users
    controller: App\Controller\UserController::preflight
    methods: [OPTIONS]