nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000/'] # URL of your React app
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Length', 'Authorization']
        allow_credentials: true # Correct option
        max_age: 3600
    paths:
        '^/': ~ # Apply CORS settings to all routes